import { motion } from "framer-motion";
import { DemoDataBadge } from "@/components/common/DemoDataBadge";
import { KnowledgeMetrics } from "@/components/knowledge/KnowledgeMetrics";

interface KnowledgeHeaderProps {
  totalItems: number;
  sourceCount: number;
  categoryCount: number;
  recentlyAddedCount: number;
}

export function KnowledgeHeader({
  totalItems,
  sourceCount,
  categoryCount,
  recentlyAddedCount,
}: KnowledgeHeaderProps) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3, ease: "easeOut" }}
      className="flex flex-col gap-6 border-b border-border pb-8"
    >
      <div>
        <div className="flex items-center gap-2.5">
          <h1 className="text-2xl font-semibold tracking-tight text-foreground sm:text-3xl">
            Knowledge Base
          </h1>
          <DemoDataBadge />
        </div>
        <p className="mt-1.5 max-w-lg text-sm text-muted-foreground sm:text-base">
          Explore learned intelligence generated by autonomous agents.
        </p>
      </div>

      <KnowledgeMetrics
        totalItems={totalItems}
        sourceCount={sourceCount}
        categoryCount={categoryCount}
        recentlyAddedCount={recentlyAddedCount}
      />
    </motion.div>
  );
}
