"""
AgentForge Planner Types.

Core data structures used by
the planning engine.
"""


from enum import Enum


from dataclasses import dataclass, field


from typing import Dict, List, Any


class PlanStatus(str, Enum):

    CREATED = "created"

    ANALYZING = "analyzing"

    PLANNED = "planned"

    EXECUTING = "executing"

    COMPLETED = "completed"

    FAILED = "failed"



class TaskStatus(str, Enum):

    PENDING = "pending"

    READY = "ready"

    RUNNING = "running"

    COMPLETED = "completed"

    FAILED = "failed"



@dataclass
class AgentGoal:
    """
    Represents the user's objective.
    """

    goal_id: str

    description: str


    metadata: Dict[str, Any] = field(
        default_factory=dict
    )



@dataclass
class PlannedTask:
    """
    Represents a task created by planner.
    """


    task_id: str

    description: str


    status: TaskStatus = (
        TaskStatus.PENDING
    )


    priority: int = 0


    dependencies: List[str] = field(
        default_factory=list
    )


    metadata: Dict[str, Any] = field(
        default_factory=dict
    )



@dataclass
class ExecutionPlan:
    """
    Complete plan generated by planner.
    """


    plan_id: str

    goal: AgentGoal


    tasks: List[PlannedTask] = field(
        default_factory=list
    )


    status: PlanStatus = (
        PlanStatus.CREATED
    )


    metadata: Dict[str, Any] = field(
        default_factory=dict
    )



@dataclass
class TaskDependency:
    """
    Represents dependency between tasks.
    """


    task_id: str


    depends_on: str


    relationship: str = "requires"

@dataclass
class ReplanRequest:
    """
    Represents a request to modify
    current execution plan.
    """


    reason: str


    failed_task_id: str


    metadata: Dict[str, Any] = field(
        default_factory=dict
    )

@dataclass
class ReplanResult:
    """
    Result after replanning.
    """


    success: bool


    new_tasks: List[PlannedTask] = field(
        default_factory=list
    )


    explanation: str = ""

@dataclass
class GoalAnalysis:
    """
    Result of goal understanding.
    """


    objective: str


    complexity: str


    requires_tools: bool = False


    required_capabilities: List[str] = field(
        default_factory=list
    )


    metadata: Dict[str, Any] = field(
        default_factory=dict
    )