"""
AgentForge Execution Context.

Maintains shared information
during agent execution.
"""


from dataclasses import dataclass, field

from typing import Dict, Any, List, Optional



@dataclass
class ExecutionContext:
    """
    Shared context across agent tasks.
    """


    task_id: str


    goal: str


    # Currently executing task

    current_task: Optional[str] = None

    



    # Results generated by previous tasks

    previous_results: List[Any] = field(
        default_factory=list
    )

    execution_history: List[Any] = field(
        default_factory=list
    )



    # Completed task tracking

    task_history: List[Dict[str, Any]] = field(
        default_factory=list
    )



    # Memory information available
    # during execution

    memory_context: Dict[str, Any] = field(
        default_factory=dict
    )



    # Additional runtime information

    metadata: Dict[str, Any] = field(
        default_factory=dict
    )

    tool_outputs: Dict[str, Any] = field(
        default_factory=dict
    )



    def set_current_task(
        self,
        task_name: str
    ):

        """
        Track currently running task.
        """

        self.current_task = task_name

    def store_tool_output(
        self,
        tool_name,
        result
    ):

        self.tool_outputs[
            tool_name
        ] = result

    def get_tool_output(
        self,
        tool_name
    ):

        return self.tool_outputs.get(
            tool_name
        )



    def add_result(
        self,
        result
    ):

        """
        Store task result.
        """


        self.previous_results.append(
            result
        )



    def add_task_history(
        self,
        task_id: str,
        description: str,
        result: Any,
        status: str
    ):

        """
        Store execution history.
        """


        self.task_history.append(

            {

                "task_id":
                    task_id,


                "description":
                    description,


                "result":
                    result,


                "status":
                    status

            }

        )



    def add_memory(
        self,
        key: str,
        value: Any
    ):

        """
        Store temporary memory
        available during workflow.
        """


        self.memory_context[key] = value



    def get_history(self):

        """
        Return previous results.
        """

        return self.previous_results



    def get_task_history(self):

        """
        Return completed task history.
        """

        return self.task_history



    def get_memory(
        self,
        key: str,
        default=None
    ):

        return self.memory_context.get(
            key,
            default
        )

    def get_last_tool_output(
        self
    ):

        if not self.tool_outputs:

            return None

        last_tool = list(

            self.tool_outputs.keys()

        )[-1]

        return self.tool_outputs[last_tool]