"""
AgentForge Workflow Runner.

Executes tasks generated by dispatcher.
"""


from core.runtime.runtime_types import (
    ExecutionStatus
)

from core.memory.memory_types import (
    MemoryType
)
from executor.tool_executor import (
    ToolExecutor
)

from core.registry.tool_selector import (
    ToolSelector
)


class WorkflowRunner:
    """
    Executes agent workflows.
    """



    def __init__(
        self,
        dispatcher,
        provider=None,
        tool_provider=None,
        memory=None,
        tools=None
    ):

        self.dispatcher = dispatcher

        self.provider = provider

        self.memory = memory

        self.tools = tools

        self.tool_selector = ToolSelector(
            tool_provider
        )

        self.tool_executor = None

        if tools:

            self.tool_executor = ToolExecutor(
                tools
            )



    async def run(
        self,
        context
    ):

        """
        Execute workflow tasks sequentially.
        """

        results = []


        tasks = (
            self.dispatcher
            .get_pending_tasks()
        )


        for task in tasks:


            try:


                # -----------------------------
                # Set current task
                # -----------------------------

                context.set_current_task(
                    task.description
                )


                task.status = (
                    ExecutionStatus.PROCESSING
                )


                # -----------------------------
                # Execute task
                # -----------------------------

                result = await self.execute_task(

                    task,

                    context

                )


                # -----------------------------
                # Store result in context
                # -----------------------------

                context.add_result(
                    result
                )


                # -----------------------------
                # Store task history
                # -----------------------------

                context.add_task_history(

                    task.task_id,

                    task.description,

                    result,

                    "completed"

                )


                # -----------------------------
                # Memory update
                # -----------------------------

                if self.memory:


                    await self.memory.store(

                        MemoryType.SESSION,

                        f"task_{task.task_id}",

                        result

                    )


                task.status = (
                    ExecutionStatus.SUCCESS
                )


                task.result = result


                results.append(
                    result
                )



            except Exception as error:


                task.status = (
                    ExecutionStatus.ERROR
                )


                task.result = str(error)


                context.add_task_history(

                    task.task_id,

                    task.description,

                    str(error),

                    "failed"

                )


                results.append(

                    {

                        "error":
                            str(error)

                    }

                )


        return results





    async def execute_task(
        self,
        task,
        context
    ):



        """
        Execute individual task.

        Decision flow:

        Task
         |
         ↓
        Tool Selector
         |
        ----------------
        |              |
        Tool          LLM
        |              |
        ↓              ↓
        Result       Gemini

        """

        # -----------------------------
        # Load previous memory context
        # -----------------------------

        if self.memory:


            previous_memory = await self.memory.retrieve(

                MemoryType.SESSION,

                "last_execution"

            )


            if previous_memory:


                context.add_memory(

                    "previous_execution",

                    previous_memory

                )



        # -----------------------------
        # Tool Selection
        # -----------------------------


        if self.tools:


            decision = await (
                self.tool_selector.select(

                    task.description,

                    self.tools.get_tool_metadata()

                )
            )



            if (
                decision.use_tool
                and
                decision.tool_name
            ):



                tool_result = await self.tool_executor.execute(

                    decision.tool_name,

                    context,

                    decision.arguments

                )


                return {

                    "type":
                        "tool_execution",


                    "tool":
                        decision.tool_name,


                    "reason":
                        decision.reason,


                    "result":
                        tool_result

                }



        # -----------------------------
        # Provider Execution
        # -----------------------------


        if self.provider:


            response = await self.provider.generate(

                self.build_task_prompt(

                    task,

                    context

                ),


                context

            )


            return response



        return {

            "task":
                task.description,


            "status":
                "completed"

        }



    def build_task_prompt(
        self,
        task,
        context
    ):


        prompt = f"""

    You are executing an agent task.


    Main Goal:

    {context.goal}



    Current Task:

    {task.description}



    Previous Task Results:

    {context.get_history()}



    Task History:

    {context.get_task_history()}



    Stored Memory Context:

    {context.memory_context}



    Use previous information
    to complete the current task.


    """


        return prompt