"""
AgentForge Workflow Runner.

Executes tasks generated by dispatcher.
"""


from core.runtime.runtime_types import (
    ExecutionStatus
)

from core.memory.memory_types import (
    MemoryType
)

from core.registry import (
    ToolSelector
)



class WorkflowRunner:
    """
    Executes agent workflows.
    """



    def __init__(
        self,
        dispatcher,
        provider=None,
        memory=None,
        tools=None
    ):

        self.dispatcher = dispatcher

        self.provider = provider

        self.memory = memory

        self.tools = tools

        self.tool_selector = (
            ToolSelector()
        )



    async def run(
        self,
        context
    ):

        """
        Execute workflow tasks.
        """


        results = []


        tasks = (
            self.dispatcher
            .get_pending_tasks()
        )


        for task in tasks:


            try:

                task.status = (
                    ExecutionStatus.PROCESSING
                )


                result = await self.execute_task(

                    task,

                    context

                )


                if self.memory:

                    await self.memory.store(

                        MemoryType.SESSION,

                        "last_execution",

                        result

                    )


                task.status = (
                    ExecutionStatus.SUCCESS
                )


                task.result = result


                context.add_result(

                    result

                )


                results.append(

                    result

                )



            except Exception as error:


                task.status = (
                    ExecutionStatus.ERROR
                )


                task.result = str(error)


                results.append(

                    {
                        "error":
                            str(error)
                    }

                )


        return results





    async def execute_task(
        self,
        task,
        context
    ):

        """
        Execute individual task.

        Decision flow:

        Task
         |
         ↓
        Tool Selector
         |
        ----------------
        |              |
        Tool          LLM
        |              |
        ↓              ↓
        Result       Gemini

        """



        # -----------------------------
        # Tool Selection
        # -----------------------------


        if self.tools:


            available_tools = (
                self.tools.list_tools()
            )


            decision = (
                self.tool_selector.select(

                    task.description,

                    available_tools

                )
            )



            if decision.use_tool:


                tool_result = await self.execute_tool(

                    decision.tool_name,

                    task

                )


                return {

                    "type":
                        "tool_execution",


                    "tool":
                        decision.tool_name,


                    "reason":
                        decision.reason,


                    "result":
                        tool_result

                }



        # -----------------------------
        # Provider Execution
        # -----------------------------


        if self.provider:


            response = await self.provider.generate(

                self.build_task_prompt(

                    task,

                    context

                ),


                context

            )


            return response



        return {

            "task":
                task.description,


            "status":
                "completed"

        }





    async def execute_tool(
        self,
        tool_name,
        task
    ):

        """
        Execute selected tool.
        """


        if not self.tools:

            return None



        tool = self.tools.get(

            tool_name

        )


        if tool:
            
            return await tool.execute(

                task.description

            )


        return {

            "error":
                "Tool not found"

        }





    def build_task_prompt(
        self,
        task,
        context
    ):

        prompt = f"""

You are executing an agent task.

Main Goal:
{context.goal}


Current Task:
{task.description}


Previous Task Results:

{context.previous_results}


Use previous information
to complete the current task.

"""


        return prompt