"""
AgentForge Tool Decision Model.

Represents AI selected tool action.
"""


from dataclasses import dataclass, field

from typing import Dict, Optional



@dataclass
class ToolDecision:
    """
    Decision generated by AI tool selector.
    """


    use_tool: bool = False


    tool_name: Optional[str] = None


    arguments: Dict = field(
        default_factory=dict
    )


    reason: str = ""